try{
'use strict';var l,m=this,aa=function(a){a.S=function(){return a.W?a.W:a.W=new a}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},n=function(a){return"array"==ba(a)},ca=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},q=function(a){return"string"==typeof a},da=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},t="closure_uid_"+(1E9*Math.random()>>>0),ea=0,fa=function(a,b,c){return a.call.apply(a.bind,
arguments)},ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},u=function(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return u.apply(null,arguments)},ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=
c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},v=Date.now||function(){return+new Date},w=function(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.D=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
var x=function(){this.s=this.s;this.o=this.o};x.prototype.s=!1;x.prototype.U=function(){this.s||(this.s=!0,this.G())};var ia=function(a,b){a.s?b.call(void 0):(a.o||(a.o=[]),a.o.push(b))};x.prototype.G=function(){if(this.o)for(;this.o.length;)this.o.shift()()};var ja=function(a){a&&"function"==typeof a.U&&a.U()};
var y=function(a,b){this.type=a;this.g=this.target=b;this.Y=!0};y.prototype.l=function(){this.Y=!1};var ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},A=function(a){return null==a?"":String(a)},la=function(a,b){return a<b?-1:a>b?1:0};var ma=function(a){y.call(this,a);this.o=0;this.h=null;this.w=this.C="";this.A=0;this.s=""};w(ma,y);var na=function(a,b,c,d,e){var f=new ma("clip_changed");f.h=a;f.o=b;f.C=c;f.w=d;e&&(f.A=e.s,f.s=e.F());return f};ma.prototype.J=function(){return A(this.h&&this.h.F()||null)};
var oa=function(a,b,c){Array.prototype.forEach.call(a,b,c)},pa=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)},qa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},ra=function(a,b){return a>b?1:a<b?-1:0};
var sa;a:{var ta=m.navigator;if(ta){var ua=ta.userAgent;if(ua){sa=ua;break a}}sa=""};var va=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},wa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),ya=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<xa.length;f++)c=xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var za="",Aa=/WebKit\/(\S+)/.exec(sa);Aa&&(za=Aa?Aa[1]:"");
var Ba=za,Ca={},Da=function(){if(!Ca["528"]){for(var a=0,b=ka(String(Ba)).split("."),c=ka("528").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"",h=/(\d*)(\D*)/g,k=/(\d*)(\D*)/g;do{var p=h.exec(f)||["","",""],r=k.exec(g)||["","",""];if(0==p[0].length&&0==r[0].length)break;a=la(0==p[1].length?0:parseInt(p[1],10),0==r[1].length?0:parseInt(r[1],10))||la(0==p[2].length,0==r[2].length)||la(p[2],r[2])}while(0==a)}Ca["528"]=0<=a}};
var Ea=null;var Fa=m.JSON.stringify;var B=function(){},C=function(a,b,c,d){a.h=null;b||(b=[]);a.w=void 0;a.s=-1;a.g=b;a:{if(a.g.length){b=a.g.length-1;var e=a.g[b];if(e&&"object"==typeof e&&!n(e)){a.o=b-a.s;a.l=e;break a}}-1<c?(a.o=c,a.l=null):a.o=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.o?(b+=a.s,a.g[b]=a.g[b]||Ga):a.l[b]=a.l[b]||Ga},Ga=[],D=function(a,b){if(b<a.o){var c=b+a.s,d=a.g[c];return d===Ga?a.g[c]=[]:d}d=a.l[b];return d===Ga?a.l[b]=[]:d},E=function(a,b,c){b<a.o?a.g[b+a.s]=c:a.l[b]=c},F=function(a,b,c){a.h||
(a.h={});if(!a.h[c]){var d=D(a,c);d&&(a.h[c]=new b(d))}return a.h[c]},G=function(a,b,c){a.h||(a.h={});var d=c?c.g:c;a.h[b]=c;E(a,b,d)},Ha=m.JSON&&m.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
B.prototype.v="function"==typeof Uint8Array?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){if(!Ea){Ea={};for(var a=0;65>a;a++)Ea[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Ea,b=[],e=0;e<this.length;e+=3){var f=this[e],g=e+1<this.length,h=g?this[e+1]:0,k=e+2<this.length,p=k?this[e+2]:0,r=f>>2,f=(f&3)<<4|h>>4,h=(h&15)<<2|p>>6,p=p&63;k||(p=64,g||(h=64));b.push(a[r],a[f],a[h],a[p])}return b.join("")};try{var b=Ha.call(null,
this.g)}finally{Uint8Array.prototype.toJSON=a}return b}:Ha?function(){return Ha.call(null,this.g)}:function(){return Fa(this.g)};B.prototype.toString=function(){return this.g.toString()};var Ia=function(a){var b;if(n(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?Ia(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?Ia(b):b);return c};
var Ka=function(a){C(this,a,-1,Ja)};w(Ka,B);var Ja=[3];Ka.prototype.getTitle=function(){return D(this,2)};Ka.prototype.setTitle=function(a){E(this,2,a)};var La=function(a){this.g=a||new Ka};La.prototype.setTitle=function(a){this.g.setTitle(a)};La.prototype.v=function(){return this.g.v()};var Ma=function(a){C(this,a,-1,null)};w(Ma,B);var I=function(a){return F(a,H,2)},H=function(a){C(this,a,-1,null)};w(H,B);var Na=function(a){return D(a,1)};var J=function(a){C(this,a,-1,null)};w(J,B);J.prototype.F=function(){return D(this,1)};var Oa=function(a){C(this,a,-1,null)};w(Oa,B);Oa.prototype.getTitle=function(){return D(this,1)};Oa.prototype.setTitle=function(a){E(this,1,a)};var Pa=function(a){C(this,a,-1,null)};w(Pa,B);var Qa=function(a){C(this,a,-1,null)};w(Qa,B);var Sa=function(a){C(this,a,23,Ra)};w(Sa,B);var Ra=[3];Sa.prototype.J=function(){return F(this,J,1)};var Ta=function(a){C(this,a,-1,null)};w(Ta,B);var Ua=function(a){this.g=a||new Ta};Ua.prototype.v=function(){return this.g.v()};var Va=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Wa=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};
var Xa="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},Ya=function(){};Ya.prototype.g=function(){throw Xa;};Ya.prototype.P=function(){return this};var K=function(a,b){this.h={};this.g=[];this.o=this.l=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof K)d=a.K(),c=a.B();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=wa(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};K.prototype.B=function(){Za(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};K.prototype.K=function(){Za(this);return this.g.concat()};
K.prototype.remove=function(a){return M(this.h,a)?(delete this.h[a],this.l--,this.o++,this.g.length>2*this.l&&Za(this),!0):!1};var Za=function(a){if(a.l!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];M(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.l!=a.g.length){for(var e={},c=b=0;b<a.g.length;)d=a.g[b],M(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};l=K.prototype;l.get=function(a,b){return M(this.h,a)?this.h[a]:b};
l.set=function(a,b){M(this.h,a)||(this.l++,this.g.push(a),this.o++);this.h[a]=b};l.forEach=function(a,b){for(var c=this.K(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new K(this)};l.P=function(a){Za(this);var b=0,c=this.o,d=this,e=new Ya;e.g=function(){if(c!=d.o)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw Xa;var e=d.g[b++];return a?e:d.h[e]};return e}; var M=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var $a=function(a){if(a.B&&"function"==typeof a.B)return a.B();if(q(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return wa(a)};var N=function(a,b){this.l=this.A=this.h="";this.C=null;this.s=this.w="";this.g=!1;var c;a instanceof N?(this.g=void 0!==b?b:a.g,ab(this,a.h),this.A=a.A,this.l=a.l,bb(this,a.C),this.w=a.w,cb(this,a.o.clone()),this.s=a.s):a&&(c=String(a).match(Va))?(this.g=!!b,ab(this,c[1]||"",!0),this.A=db(c[2]||""),this.l=db(c[3]||"",!0),bb(this,c[4]),this.w=db(c[5]||"",!0),cb(this,c[6]||"",!0),this.s=db(c[7]||"")):(this.g=!!b,this.o=new O(null,0,this.g))};
N.prototype.toString=function(){var a=[],b=this.h;b&&a.push(eb(b,fb,!0),":");var c=this.l;if(c||"file"==b)a.push("//"),(b=this.A)&&a.push(eb(b,fb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.C,null!=c&&a.push(":",String(c));if(c=this.w)this.l&&"/"!=c.charAt(0)&&a.push("/"),a.push(eb(c,"/"==c.charAt(0)?gb:hb,!0));(c=this.o.toString())&&a.push("?",c);(c=this.s)&&a.push("#",eb(c,ib));return a.join("")};N.prototype.clone=function(){return new N(this)};
var ab=function(a,b,c){a.h=c?db(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))},bb=function(a,b){if(b){b=+b;if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.C=b}else a.C=null},cb=function(a,b,c){b instanceof O?(a.o=b,jb(a.o,a.g)):(c||(b=eb(b,kb)),a.o=new O(b,0,a.g))},lb=function(a){a instanceof N?a.clone():new N(a,void 0)},db=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},eb=function(a,b,c){return q(a)?(a=encodeURI(a).replace(b,mb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},mb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},fb=/[#\/\?@]/g,hb=/[\#\?:]/g,gb=/[\#\?]/g,kb=/[\#\?@]/g,ib=/#/g,O=function(a,b,c){this.h=this.g=null;this.l=a||null;this.o=!!c},P=function(a){a.g||(a.g=new K,a.h=0,a.l&&Wa(a.l,function(b,c){var d=decodeURIComponent(b.replace(/\+/g," "));P(a);a.l=null;var d=Q(a,d),e=a.g.get(d);e||a.g.set(d,e=[]);e.push(c);a.h=a.h+1}))};
O.prototype.remove=function(a){P(this);a=Q(this,a);return M(this.g.h,a)?(this.l=null,this.h=this.h-this.g.get(a).length,this.g.remove(a)):!1};var nb=function(a,b){P(a);b=Q(a,b);return M(a.g.h,b)};l=O.prototype;l.K=function(){P(this);for(var a=this.g.B(),b=this.g.K(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};l.B=function(a){P(this);var b=[];if(q(a))nb(this,a)&&(b=pa(b,this.g.get(Q(this,a))));else{a=this.g.B();for(var c=0;c<a.length;c++)b=pa(b,a[c])}return b};
l.set=function(a,b){P(this);this.l=null;a=Q(this,a);nb(this,a)&&(this.h=this.h-this.g.get(a).length);this.g.set(a,[b]);this.h=this.h+1;return this};l.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};l.toString=function(){if(this.l)return this.l;if(!this.g)return"";for(var a=[],b=this.g.K(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.l=a.join("&")};
l.clone=function(){var a=new O;a.l=this.l;this.g&&(a.g=this.g.clone(),a.h=this.h);return a};var Q=function(a,b){var c=String(b);a.o&&(c=c.toLowerCase());return c},jb=function(a,b){b&&!a.o&&(P(a),a.l=null,a.g.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.l=null,this.g.set(Q(this,e),qa(a)),this.h=this.h+a.length))},a));a.o=b};
var ob=function(a){this.g=a||new Oa;a=D(this.g,3);E(this.g,3,a)};ob.prototype.getTitle=function(){return A(this.g.getTitle())};ob.prototype.setTitle=function(a){this.g.setTitle(a)};ob.prototype.v=function(){return this.g.v()};var pb=function(){this.h="";this.g=null},qb=function(a){var b=new pb;b.h=a;b.g=0};qb("<!DOCTYPE html>");qb("");qb("<br>");var sb=function(a){this.g=new K;if(a){a=$a(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.g.set(rb(d),d)}}},rb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[t]||(a[t]=++ea)):b.substr(0,1)+a};l=sb.prototype;l.removeAll=function(a){a=$a(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};l.remove=function(a){return this.g.remove(rb(a))};l.B=function(){return this.g.B()};l.clone=function(){return new sb(this)};l.P=function(){return this.g.P(!1)};
var ub=function(a,b,c,d,e){"number"==typeof e||tb++;this.l=d||v();this.o=a;this.s=b;this.h=c;delete this.g};ub.prototype.g=null;var tb=0;ub.prototype.getMessage=function(){return this.s};var vb=function(a){this.o=a;this.h=this.l=this.g=null},wb=function(a,b){this.name=a;this.value=b};wb.prototype.toString=function(){return this.name};var xb=new wb("SHOUT",1200),yb=new wb("SEVERE",1E3),zb=new wb("WARNING",900),Ab=new wb("INFO",800),Bb=new wb("CONFIG",700);vb.prototype.getChildren=function(){this.h||(this.h={});return this.h};var Cb=function(a){return a.l?a.l:a.g?Cb(a.g):null};
vb.prototype.log=function(a,b,c){if(a.value>=Cb(this).value)for("function"==ba(b)&&(b=b()),a=new ub(a,String(b),this.o),c&&(a.g=c),c="log:"+a.getMessage(),m.console&&(m.console.timeStamp?m.console.timeStamp(c):m.console.markTimeline&&m.console.markTimeline(c)),m.msWriteProfilerMark&&m.msWriteProfilerMark(c),c=this;c;)c=c.g}; var Db={},Eb=null,Fb=function(){Eb||(Eb=new vb(""),Db[""]=Eb,Eb.l=Bb)},Gb=function(a){Fb();var b;if(!(b=Db[a])){b=new vb(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Gb(a.substr(0,c));c.getChildren()[d]=b;b.g=c;Db[a]=b}return b};
Gb("gws.collections.models.IndexedClips");Gb("gws.collections.models.IndexedFolios");var Hb=function(){};aa(Hb);var Ib={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},Jb=function(a){return Ib[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+v().toString(36)};var Kb=function(a,b,c){y.call(this,c||"TRANSACTION_COMMIT");this.s=a||0;(a=b)||(Hb.S(),a=Jb(2));this.o=a;this.h=[];this.w=[]};w(Kb,y);var Mb=function(a,b,c){a.h.push(b);a.w.push(c);Lb(c,b)};Kb.prototype.F=function(){return this.o};Da();Da();var Nb=function(a,b){y.call(this,a?a.type:"");this.h=this.g=this.target=null;a&&(this.type=a.type,this.target=a.target||a.srcElement,this.g=b,this.h=a,a.defaultPrevented&&this.l())};w(Nb,y);Nb.prototype.l=function(){Nb.L.l.call(this);var a=this.h;a.preventDefault?a.preventDefault():a.returnValue=!1};
var Ob="closure_listenable_"+(1E6*Math.random()|0),Pb=0;var Qb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.R=!!d;this.N=e;this.V=++Pb;this.removed=this.M=!1},Rb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.N=null};var Sb=function(a){this.src=a;this.g={};this.h=0},Ub=function(a,b,c,d,e){var f=b.toString();b=a.g[f];b||(b=a.g[f]=[],a.h++);var g=Tb(b,c,d,e);-1<g?(a=b[g],a.M=!1):(a=new Qb(c,a.src,f,!!d,e),a.M=!1,b.push(a));return a};Sb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=Tb(e,b,c,d);return-1<b?(Rb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};
var Vb=function(a,b){var c=b.type,d;if(d=c in a.g){d=a.g[c];var e;e=Array.prototype.indexOf.call(d,b,void 0);var f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);d=f}d&&(Rb(b),0==a.g[c].length&&(delete a.g[c],a.h--))};Sb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,Rb(d[e]);delete this.g[c];this.h--}return b}; var Wb=function(a,b,c,d,e){a=a.g[b.toString()];b=-1;a&&(b=Tb(a,c,d,e));return-1<b?a[b]:null},Tb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.R==!!c&&f.N==d)return e}return-1};
var Xb="closure_lm_"+(1E6*Math.random()|0),Yb={},Zb=0,$b=function(a,b,c,d,e){if(n(b)){for(var f=0;f<b.length;f++)$b(a,b[f],c,d,e);return null}c=ac(c);if(a&&a[Ob])a=a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=bc(a);g||(a[Xb]=g=new Sb(a));c=Ub(g,b,c,d,e);if(!c.proxy){d=cc();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(dc(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
Zb++}a=c}return a},cc=function(){var a=ec,b=function(c){return a.call(b.src,b.listener,c)};return b},fc=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)fc(a,b[f],c,d,e);else c=ac(c),a&&a[Ob]?a.unlisten(b,c,d,e):a&&(a=bc(a))&&(b=Wb(a,b,c,!!d,e))&&gc(b)},gc=function(a){if("number"!=typeof a&&a&&!a.removed){var b=a.src;if(b&&b[Ob])Vb(b.h,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.R):b.detachEvent&&b.detachEvent(dc(c),d);Zb--;(c=bc(b))?(Vb(c,a),0==c.h&&(c.src=
null,b[Xb]=null)):Rb(a)}}},dc=function(a){return a in Yb?Yb[a]:Yb[a]="on"+a},ec=function(a,b){var c;if(a.removed)c=!0;else{c=new Nb(b,this);var d=a.listener,e=a.N||a.src;a.M&&gc(a);c=d.call(e,c)}return c},bc=function(a){a=a[Xb];return a instanceof Sb?a:null},hc="__closure_events_fn_"+(1E9*Math.random()>>>0),ac=function(a){if("function"==ba(a))return a;a[hc]||(a[hc]=function(b){return a.handleEvent(b)});return a[hc]};
var R=function(){x.call(this);this.h=new Sb(this);this.Z=this;this.C=null};w(R,x);R.prototype[Ob]=!0;R.prototype.removeEventListener=function(a,b,c,d){fc(this,a,b,c,d)};
var Lb=function(a,b){var c,d=a.C;if(d)for(c=[];d;d=d.C)c.push(d);var d=a.Z,e=b,f=e.type||e;if(q(e))e=new y(e,d);else if(e instanceof y)e.target=e.target||d;else{var g=e,e=new y(f,d);ya(e,g)}var g=!0,h;if(c)for(var k=c.length-1;0<=k;k--)h=e.g=c[k],g=ic(h,f,!0,e)&&g;h=e.g=d;g=ic(h,f,!0,e)&&g;g=ic(h,f,!1,e)&&g;if(c)for(k=0;k<c.length;k++)h=e.g=c[k],g=ic(h,f,!1,e)&&g};R.prototype.G=function(){R.L.G.call(this);this.h&&this.h.removeAll(void 0);this.C=null};
R.prototype.listen=function(a,b,c,d){return Ub(this.h,String(a),b,c,d)};R.prototype.unlisten=function(a,b,c,d){return this.h.remove(String(a),b,c,d)};var ic=function(a,b,c,d){b=a.h.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.R==c){var h=g.listener,k=g.N||g.src;g.M&&Vb(a.h,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.Y};
var jc=function(){R.call(this)};w(jc,R);var kc=function(a){R.call(this);this.g=a};w(kc,jc);kc.prototype.F=function(){return this.g.J()?A(this.g.J().F()):""};kc.prototype.v=function(){return this.g.v()};var lc=function(a){x.call(this);this.h=a;this.g={}};w(lc,x);var mc=[];l=lc.prototype;l.listen=function(a,b,c,d){n(b)||(b&&(mc[0]=b.toString()),b=mc);for(var e=0;e<b.length;e++){var f=$b(a,b[e],c||this.handleEvent,d||!1,this.h||this);if(!f)break;this.g[f.V]=f}return this};
l.unlisten=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.h||this,c=ac(c),d=!!d,b=a&&a[Ob]?Wb(a.h,String(b),c,d,e):a?(a=bc(a))?Wb(a,b,c,d,e):null:null,b&&(gc(b),delete this.g[b.V]);return this};l.removeAll=function(){va(this.g,function(a,b){this.g.hasOwnProperty(b)&&gc(a)},this);this.g={}};l.G=function(){lc.L.G.call(this);this.removeAll()};l.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var oc=function(a){this.g=a||new Ma;if(!I(this.g)){a=this.g;var b=new H;G(a,2,b)}F(this.g,H,3)||(a=this.g,b=new H,G(a,3,b));this.h=new N(A(Na(I(this.g))));new N(nc(this))},nc=function(a){return A(Na(F(a.g,H,3))).replace(/^\/\//,"https://")};oc.prototype.v=function(){return this.g.v()};
var pc=function(a){this.g=a||new Pa};pc.prototype.v=function(){return this.g.v()};var qc=function(a){this.g=a||new Qa};qc.prototype.setSize=function(a,b){E(this.g,2,a);E(this.g,3,b)};qc.prototype.v=function(){return this.g.v()};var sc=function(a,b){va(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:rc.hasOwnProperty(d)?a.setAttribute(rc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},rc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},uc=function(a,b,c){var d=arguments,
e=document,f=d[1],g=e.createElement(d[0]);f&&(q(f)?g.className=f:n(f)?g.className=f.join(" "):sc(g,f));2<d.length&&tc(e,g,d);return g},tc=function(a,b,c){function d(c){c&&b.appendChild(q(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ca(f)||da(f)&&0<f.nodeType?d(f):oa(vc(f)?qa(f):f,d)}},vc=function(a){if(a&&"number"==typeof a.length){if(da(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==ba(a))return"function"==typeof a.item}return!1};
var T=function(a){kc.call(this,a||new Sa);this.l=wc(this);this.w=S(this);this.H=xc(this);a=this.g;a.h||(a.h={});if(!a.h[3]){for(var b=D(a,3),c=[],d=0;d<b.length;d++)c[d]=new Ta(b[d]);a.h[3]=c}b=a.h[3];b==Ga&&(b=a.h[3]=[]);a=b;for(b=0;b<a.length;b++)c=new Ua(a[b]),F(c.g,J,1).F();a=F(this.g,Qa,10);!this.A&&a&&(this.A=new qc(a));this.A=this.A||null;a=F(this.g,Pa,13);!this.I&&a&&(this.I=new pc(a));this.I=this.I||null;new sb;this.F()||(Hb.S(),a=Jb(0),this.g.J()||(b=new J,G(this.g,1,b)),b=this.g.J(),E(b,
1,a))};w(T,kc);Gb("gws.collections.models.ClipModel");T.prototype.clone=function(){var a;a=this.g;a=new a.constructor(Ia(a.g));return new T(a)};var wc=function(a){var b=F(a.g,Ma,5);!a.l&&b&&(a.l=new oc(b));if(!a.l&&3==D(a.g,4)){var b=xc(a),b=A(D(b.g,1)).replace(/\//g,"-"),b="https://www.gstatic.com/vd/kp/%s/en/1/image.jpg".replace("%s",b),c=uc("img");c.src=b;c.onload=u(a.O,a,c)}return a.l||null};
T.prototype.O=function(a){var b=new oc,c=a.src,d=F(b.g,H,3);E(d,1,c);new N(nc(b));c=a.naturalWidth;a=a.naturalHeight;d=F(b.g,H,3);E(d,2,c);c=F(b.g,H,3);E(c,3,a);var c=a=new Kb(3),d=this.l&&this.l.v(),e=b.v();d!=e&&(this.l=b,G(this.g,5,b.g),b=v(),E(this.g,8,b),b=na(this,203,d||"",e,c),Mb(c,b,this),c!=a&&0<c.h.length&&Lb(this,c))};var xc=function(a){var b=F(a.g,Ka,9);!a.H&&b&&(a.H=new La(b));return a.H||null},S=function(a){var b=F(a.g,Oa,6);!a.w&&b&&(a.w=new ob(b));return a.w||null};
T.prototype.getTitle=function(){return S(this)?S(this).getTitle().toString():""};T.prototype.setTitle=function(a,b){var c=b||new Kb;if(S(this).getTitle()==a)return!1;var d=S(this).v(),e=S(this);e.setTitle(a);var f=v();E(this.g,8,f);d=na(this,204,d,e.v(),c);Mb(c,d,this);c!=b&&0<c.h.length&&Lb(this,c);return!0};var yc=function(a,b){var c=new Kb,d=D(a.g,4);D(a.g,4)!=b&&(E(a.g,4,b),d=na(a,206,""+d,""+b,c),Mb(c,d,a),void 0!=c&&0<c.h.length&&Lb(a,c))}; T.prototype.toString=function(){return"ClipModel:"+this.F()};
var zc=function(a){x.call(this);this.l=a;this.g={};this.h={}};w(zc,x);zc.prototype.G=function(){this.unlisten();zc.L.G.call(this)};zc.prototype.listen=function(a,b){var c=u(b,this.l);a.addListener(c);var d=a[t]||(a[t]=++ea);d in this.g?this.h[d].g.set(rb(c),c):(this.g[d]=a,this.h[d]=new sb([c]));return this};zc.prototype.unlisten=function(a){if(a){var b=a[t]||(a[t]=++ea);if(b in this.g){var c=this.h[b].B();oa(c,a.removeListener,a);delete this.h[b];delete this.g[b]}}else va(this.g,this.unlisten,this)};
var Ac=function(){R.call(this);this.O=new lc(this);ia(this,ha(ja,this.O))};w(Ac,R);Ac.prototype.l=function(a){this.C=a};var Bc=function(a,b){this.width=a;this.height=b},Cc=function(a){return a.width*a.height};var U=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.D=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}},Dc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ec={IMG:" ",BR:"\n"},Fc=/&([^;\s<&]+);?/g,V=function(a,b){var c=Gc(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},Ic=function(a){if("none"!=
V(a,"display"))return Hc(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Hc(a);b.display=c;b.position=e;b.visibility=d;return a},Hc=function(a){var b=a.offsetWidth,c=a.offsetHeight;return void 0===b||!b&&!c?(a=a.getBoundingClientRect(),new Bc(a.right-a.left,a.bottom-a.top)):new Bc(b,c)},Gc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Jc=function(a){if(a.parentElement)return a.parentElement;a=a.parentNode;
return"object"==typeof a&&1==a.nodeType?a:null},Lc=function(a){var b=[];Kc(a,b);a=b.join("");a=a.replace(/ +/g," ");" "!=a&&(a=a.replace(/^\s*/,""));return a},Kc=function(a,b){if(!(a.nodeName in Dc))if(3==a.nodeType)b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,""));else if(a.nodeName in Ec)b.push(Ec[a.nodeName]);else for(var c=a.firstChild;c;)Kc(c,b),c=c.nextSibling},Mc=function(a){if(-1==a.indexOf("&"))return a;var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=document.createElement("div");
return a.replace(Fc,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=+("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},Nc=function(a){return a&&5<=a.length?"d"==a.charAt(0)&&"a"==a.charAt(1)&&"t"==a.charAt(2)&&"a"==a.charAt(3)&&":"==a.charAt(4):!1};
var Oc=function(){this.g=["ad","advertisement","ads","sponsor","sponsored"]};Oc.prototype.filter=function(a){for(;a;){for(var b=a.classList,c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=this.g.indexOf(d[e].toLowerCase()))return!1;a=Jc(a)}return!0};
var Pc=function(a){this.h=a},Qc=function(a,b){return a==b?0:a.h-b.h};var W=function(){this.o=[]};W.prototype.filter=function(a){for(var b=0;b<this.o.length;++b)if(!this.o[b].filter(a))return!1;return!0};var Rc=function(a,b){var c=a.g(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.h>d.h&&(d=f)}return d};W.prototype.g=function(a){return X(this,a.getElementsByTagName("*"))};var X=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.h(b[f],c);g&&d.push(g)}return d};W.prototype.h=function(){return null};
var Y=function(a,b,c,d){Y.D(this,"constructor",a);this.g=b;this.l=c;this.o=d};U(Y,Pc);var Sc=function(){};Sc.prototype.filter=function(a){for(;a;){if("none"==V(a,"display"))return!1;var b=Ic(a);if("hidden"==V(a,"overflow")&&0==Cc(b)||"hidden"==V(a,"visibility"))return!1;a=Jc(a)}return!0};var Tc=function(){Tc.D(this,"constructor");this.o.push(new Oc);this.o.push(new Sc);this.l=document.createElement("a")};U(Tc,W);var Uc={".gif":.5},Vc=function(){this.X=0;this.T={}};Tc.prototype.g=function(a){return X(this,a.getElementsByTagName("*"),new Vc)};
Tc.prototype.h=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=Wc(this,a,1,"property","og:image","content")||Wc(this,a,.9,"name","msapplication-tileimage","content")||Wc(this,a,.8,"name","twitter:image","content")||Xc(a);break;case "link":c=Wc(this,a,.7,"rel","apple-touch-icon","href")||Wc(this,a,.6,"rel","image_src","href")||Xc(a);break;case "img":if(this.filter(a))a:{if((c=a.src)&&!Nc(c)){var d=new Bc(a.naturalWidth,a.naturalHeight),e=Ic(a),f=Cc(d)<Cc(e)?d:e;if(f.width&&f.height){f=
Yc(a);c=new Y(f,c,d,e);break a}}c=null}break;default:if(this.filter(a)&&30>b.X){a:{c=V(a,"background-image");d=V(a,"background-repeat");e=V(a,"background-size");if(c&&("no-repeat"==d||"cover"==e)&&c&&5<=c.length&&"u"==c.charAt(0)&&"r"==c.charAt(1)&&"l"==c.charAt(2)&&"("==c.charAt(3)&&")"==c.charAt(c.length-1)&&(d=4,e=c.length-1,'"'==c.charAt(d)&&'"'==c.charAt(e-1)&&(d++,e--),(c=c.substring(d,e))&&!Nc(c)&&(d=Ic(a),d.width&&d.height))){for(var e=Yc(a),f=a.children,g=0;g<f.length;++g){var h=f[g];if("none"!=
V(h,"display")&&Cc(Ic(h))>.1*Cc(d)){e*=.1;break}}c=new Y(e,c,void 0,d);break a}c=null}c&&++b.X}}if(!c)return null;e=c.o||c.l;if(c.g!=document.location.href&&(100>e.width||100>e.height))return null;d=c.h;d/=1+Math.exp(-1E-5*Cc(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.g;this.l.href=e;e=this.l.href;f=decodeURIComponent(this.l.pathname||"");g=f.lastIndexOf(".");0<g&&(f=Uc[f.slice(g)])&&(d*=f);if(e in b.T&&b.T[e]>d)return null;b.T[e]=d;return new Y(d,e,c.l,c.o)};
var Wc=function(a,b,c,d,e,f){if(b.hasAttribute(d)&&b.getAttribute(d).toLowerCase()==e.toLowerCase()){d=b.getAttribute(f);if(!d||Nc(d))return null;e=parseInt(b.getAttribute("data-google-stars-image-width"),10);f=parseInt(b.getAttribute("data-google-stars-image-height"),10);if(e&&f)return b=Gc(b),a.l.href=b.documentURI,"/"!=a.l.pathname&&-1==b.body.innerHTML.indexOf(d)&&(c*=.5),new Y(c,d,new Bc(e,f))}return null},Xc=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=
a.getAttribute("href")||a.getAttribute("content");if(!b||Nc(b))return null;var c=parseInt(a.getAttribute("data-google-stars-image-width"),10);a=parseInt(a.getAttribute("data-google-stars-image-height"),10);if(c&&a)return new Y(.55,b,new Bc(c,a))}return null},Yc=function(a){var b=Gc(a);if(a==b.documentElement)a=0;else{var c=b.body||b.documentElement,b=b.defaultView.pageYOffset||c.scrollTop;a=a.getBoundingClientRect().top+b}return 2E3<a?0:1/(1+Math.exp(.001*a))};
var Zc=function(a,b){Zc.D(this,"constructor",a);this.g=b};U(Zc,Pc);var $c=function(){$c.D(this,"constructor")};U($c,W);
$c.prototype.g=function(a){var b=X(this,a.getElementsByTagName("meta")),c;if(a.body){for(var d=c="",e=0,f=a.body.innerText.replace(/(\r\n|\r)/g,"\n"),g=f.split("\n"),h=0;h<g.length;++h){c=g[h].trim().replace(/\s+/g," ");for(var k=c.split(" "),p=k.length,r,z=r=0;z<c.length;++z){var L=c.charAt(z);("a"<=L&&"z">=L||"A"<=L&&"Z">=L)&&++r}if(z=64<=c.length&&8<=p&&r>=.4*c.length){for(L=z=0;L<c.length;++L)/[^a-zA-Z0-9\r\n\t ]/.test(c.charAt(L))&&++z;z=0<z}if(z&&24>=ad(k))break;r>=.4*c.length&&p>e&&24>=ad(k)&&
(d=c,e=p);c=""}0==c.length&&20<d.length&&4<=e&&(c=d);f=f.trim().replace(/[\t\n ]+/g," ");c=new Zc(.1,c||f.substring(0,1024))}else c=null;c&&b.push(c);if(a=a.defaultView)a=a.getSelection().toString(),0<a.length&&b.push(new Zc(1,a));return b};
$c.prototype.h=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}do a=c,c=Mc(c);while(c!=a);c=c.replace(/<[^<>]*?>/g,"");c=c.trim();return 5<c.length?(1024<c.length&&(c=c.substr(0,1021)+"..."),new Zc(b,c)): null};var ad=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var bd=function(a,b){bd.D(this,"constructor",a);this.g=b};U(bd,Pc);var cd=function(a){return a.g};var dd=function(a,b,c){dd.D(this,"constructor",a);this.l=b;this.g=c};U(dd,Pc);var ed=function(a,b,c,d){this.l=a;this.g=b;this.h=c;this.o=d};ed.prototype.getTitle=function(){return this.l};var fd=function(){fd.D(this,"constructor")};U(fd,W);fd.prototype.g=function(a){var b=X(this,a.getElementsByTagName("meta")).concat(X(this,a.getElementsByTagName("title"))),c=X(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=b.concat(c)):(c=X(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=b.concat(c)):(c=X(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=b.concat(c))));a.title&&b.push(new bd(1,a.title));b.push(new bd(.1,a.documentURI));return b};
fd.prototype.h=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=Lc(a);break;case "h1":b=.4;c=Lc(a);break;case "h2":b=.3;c=Lc(a);break;case "h3":b=.2;c=Lc(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=c.trim();do a=c,c=Mc(c);while(a!=c);return 1< c.length?new bd(b,c):null};
var gd=function(){gd.D(this,"constructor")};U(gd,W);gd.prototype.h=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;a:{if(a.hasAttribute("property")&&"og:video"==a.getAttribute("property").toLowerCase()){b=a.getAttribute("content");var c=parseInt(a.getAttribute("data-google-stars-video-width"),10);a=parseInt(a.getAttribute("data-google-stars-video-height"),10);if(b&&0<c&&0<a){b=new dd(1,b,new Bc(c,a));break a}}b=null}return b}return null};
var hd=function(){this.l=new fd;this.h=new $c;this.g=new Tc;this.o=new gd};var id=function(){this.g=0;this.l=Promise.resolve();this.h=null},ld=function(a){if(0==a.g){var b=document.getElementsByTagName("meta"),c=document.getElementsByTagName("link");a.g=b.length+c.length;if(0<a.g){a.l=new Promise(function(a){this.h=a}.bind(a));for(var d=0;d<b.length;d++)jd(a,b[d]);for(d=0;d<c.length;d++)kd(a,c[d]);setTimeout(a.h,5E3)}else a.l=Promise.resolve()}return a.l},jd=function(a,b){var c="";if(b.hasAttribute("property"))switch(b.getAttribute("property").toLowerCase()){case "og:image":var c=
b.getAttribute("content"),d=Jc(b).children,e=md(d,"og:image:width"),d=md(d,"og:image:height");0<e&&0<d&&(b.setAttribute("data-google-stars-image-width",e),b.setAttribute("data-google-stars-image-height",d));break;case "og:video":d=Jc(b).children,e=md(d,"og:video:width"),d=md(d,"og:video:height"),0<e&&0<d&&(b.setAttribute("data-google-stars-video-width",e),b.setAttribute("data-google-stars-video-height",d))}else if(b.hasAttribute("name"))switch(b.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":c=
b.getAttribute("content")}else if(b.hasAttribute("itemprop"))switch(b.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":c=b.getAttribute("href")||b.getAttribute("content")}nd(a,c,b)},kd=function(a,b){var c="";if(b.hasAttribute("rel"))switch(b.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":c=b.getAttribute("href")}else if(b.hasAttribute("itemprop"))switch(b.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":c=b.getAttribute("href")||
b.getAttribute("content")}nd(a,c,b)},md=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},nd=function(a,b,c){!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height")?0==--a.g&&a.h():od(a,b,a.o.bind(a,c))},od=function(a,b,c){var d=new Image,e=function(b){"load"==b.type&&c(d.naturalWidth,d.naturalHeight);0==--a.g&&
a.h();d.removeEventListener("load",e);d.removeEventListener("error",e)};d.addEventListener("load",e);d.addEventListener("error",e);d.src=b};id.prototype.o=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var pd=function(){Ac.call(this);this.g=null;this.H=new id;this.w=null;this.A=new zc(this);ia(this,ha(ja,this.A))};w(pd,Ac);var qd=Gb("image.collections.extension.ContentController");pd.prototype.l=function(a){pd.L.l.call(this,a);this.A.listen(chrome.runtime.onMessage,this.$)};
pd.prototype.$=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.g){b=a.clipId;c=a.userId;a=new J;E(a,1,b);E(a,2,c);b=new Sa;G(b,1,a);a=v();E(b,7,a);E(b,8,a);this.g=new T(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?yc(this.g,1):yc(this.g,2);a=new ob;try{lb(b)}catch(d){b=encodeURI(b)}try{lb(b)}catch(d){b=""}E(a.g,3,b);b=this.g;b.w=a;G(b.g,6,a.g);ld(this.H).then(u(this.I,this,!0))}else qd&&qd.log(zb,"Clip is already being created",void 0);
break;case "get_salient_images":ld(this.H).then(u(this.I,this,!1));break;default:qd&&qd.log(yb,"Invalid message type: "+a.type,void 0)}};
pd.prototype.I=function(a){this.w||(this.w=new hd);var b,c=this.w,d=document,e=Rc(c.l,d);b=Rc(c.h,d);for(var f=c.g.g(d),c=Rc(c.o,d),d=0,g={},h=0;h<f.length;h++)g[f[h].g]||(g[f[h].g]=!0,f[d++]=f[h]);f.length=d;b=new ed(e,b,f,c);f=b.h;f.sort(Qc||ra);e=[];d=null;for(c=0;c<f.length;c++){g=d=new oc;h=f[c].g;g.h=null;try{var k=I(g.g);E(k,1,h);g.h=new N(A(Na(I(g.g))))}catch(z){h=I(g.g),E(h,1,void 0),h=I(g.g),E(h,2,void 0),h=I(g.g),E(h,3,void 0)}g.h&&D(g.g,6)&&E(g.g,6,!1);var p=f[c].l;if(p){var g=d,h=p.width,
p=p.height,r=I(g.g);E(r,2,h);g=I(g.g);E(g,3,p)}e.unshift(d.v())}if(a){!wc(this.g)&&d&&(a=this.g,k=d,a.l=k,G(a.g,5,k.g),k=v(),E(a.g,8,k));a=S(this.g);!a.getTitle()&&b.getTitle()&&a.setTitle(cd(b.getTitle()));!A(D(a.g,2))&&b.g&&E(a.g,2,b.g.g);if(k=b.o)yc(this.g,4),a=new qc,E(a.g,1,k.l),a.setSize(k.g.width,k.g.height),k=this.g,k.A=a,G(k.g,10,a.g);chrome.runtime.sendMessage({type:"created_clip",clipData:this.g.v(),images:e});this.g=null}else chrome.runtime.sendMessage({type:"salient_images_found",images:e})};
var rd=function(){this.g=v()},sd=new rd;rd.prototype.set=function(a){this.g=a};rd.prototype.get=function(){return this.g};var td=function(a){this.o=a||"";this.s=sd};td.prototype.g=!0;td.prototype.h=!0;td.prototype.l=!1;var Z=function(a){return 10>a?"0"+a:String(a)},ud=function(a,b){var c=(a.l-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},vd=function(a){td.call(this,a)};w(vd,td);
var wd=function(){u(this.o,this);this.g=new vd;this.g.h=!1;this.g.l=!1;this.h=this.g.g=!1;this.l="";this.s={}};
wd.prototype.o=function(a){if(!this.s[a.h]){var b;b=this.g;var c=[];c.push(b.o," ");if(b.h){var d=new Date(a.l);c.push("[",Z(d.getFullYear()-2E3)+Z(d.getMonth()+1)+Z(d.getDate())+" "+Z(d.getHours())+":"+Z(d.getMinutes())+":"+Z(d.getSeconds())+"."+Z(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",ud(a,b.s.get()),"s] ");c.push("[",a.h,"] ");c.push(a.getMessage());b.l&&(d=a.g)&&c.push("\n",d instanceof Error?d.message:d.toString());b.g&&c.push("\n");b=c.join("");if(c=xd)switch(a.o){case xb:yd(c, "info",b);break;case yb:yd(c,"error",b);break;case zb:yd(c,"warn",b);break;default:yd(c,"debug",b)}else this.l+=b}};var xd=m.console,yd=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var zd=function(){R.call(this);this.g=new pd;ia(this,ha(ja,this.g))};w(zd,R);aa(zd);var Ad=new wd;0!=Ad.h&&(Fb(),Ad.h=!1);var Bd=Gb("image.collections.extension.Content"),Cd=zd.S();Bd&&Bd.log(Ab,"Initializing extension content",void 0);Cd.g.l(Cd);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
