try{
'use strict';var f=this,g=function(){},m=function(a){a.v=function(){return a.B?a.B:a.B=new a}},aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=
typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},n=function(a){return"function"==aa(a)},ba=function(a,b,c){return a.call.apply(a.bind,arguments)},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);
return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},p=function(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return p.apply(null,arguments)},r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},da=Date.now||function(){return+new Date};
var t;a:{var u=f.navigator;if(u){var v=u.userAgent;if(v){t=v;break a}}t=""};var w=function(a){a()},ea=function(a){var b=document.body;b&&a&&w(function(){b.appendChild(a)})},fa=function(a,b){w(function(){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(String(b)))}})};
var x=function(a,b,c){this.o=c;this.l=a;this.s=b;this.h=0;this.g=null};x.prototype.get=function(){var a;0<this.h?(this.h--,a=this.g,this.g=a.next,a.next=null):a=this.l();return a};var y=function(a,b){a.s(b);a.h<a.o&&(a.h++,b.next=a.g,a.g=b)};var z=function(a){f.setTimeout(function(){throw a;},0)},A,ga=function(){var a=f.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==t.indexOf("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+
b.location.host,a=p(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==t.indexOf("Trident")&&-1==t.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.A;c.A=null;a()}};return function(a){d.next={A:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in
document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){f.setTimeout(a,0)}};
var B=function(){this.h=this.g=null},E=new x(function(){return new D},function(a){a.reset()},100);B.prototype.remove=function(){var a=null;this.g&&(a=this.g,this.g=this.g.next,this.g||(this.h=null),a.next=null);return a};var D=function(){this.next=this.h=this.g=null};D.prototype.set=function(a,b){this.g=a;this.h=b;this.next=null};D.prototype.reset=function(){this.next=this.h=this.g=null};
var I=function(a,b){F||ha();G||(F(),G=!0);var c=H,d=E.get();d.set(a,b);c.h?c.h.next=d:c.g=d;c.h=d},F,ha=function(){if(f.Promise&&f.Promise.resolve){var a=f.Promise.resolve(void 0);F=function(){a.then(J)}}else F=function(){var a=J,c;!(c=!n(f.setImmediate))&&(c=f.Window&&f.Window.prototype)&&(c=-1==t.indexOf("Edge")&&f.Window.prototype.setImmediate==f.setImmediate);c?(A||(A=ga()),A(a)):f.setImmediate(a)}},G=!1,H=new B,J=function(){for(var a=null;a=H.remove();){try{a.g.call(a.h)}catch(b){z(b)}y(E,a)}G= !1};
var L=function(a,b){this.g=0;this.C=void 0;this.l=this.h=this.o=null;this.s=this.w=!1;if(a!=g)try{var c=this;a.call(b,function(a){K(c,2,a)},function(a){K(c,3,a)})}catch(d){K(this,3,d)}},M=function(){this.next=this.l=this.h=this.o=this.g=null;this.s=!1};M.prototype.reset=function(){this.l=this.h=this.o=this.g=null;this.s=!1};
var N=new x(function(){return new M},function(a){a.reset()},100),O=function(a,b,c){var d=N.get();d.o=a;d.h=b;d.l=c;return d},ia=function(a,b,c){P(a,b,c,null)||I(r(b,a))},ja=function(a){return new L(function(b,c){var d=a.length,e=[];if(d)for(var k=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},l=0,q;l<a.length;l++)q=a[l],ia(q,r(k,l),h);else b(e)})};L.prototype.then=function(a,b,c){return ka(this,n(a)?a:null,n(b)?b:null,c)};L.prototype.then=L.prototype.then;L.prototype.$goog_Thenable=!0;
var R=function(a,b){a.h||2!=a.g&&3!=a.g||Q(a);a.l?a.l.next=b:a.h=b;a.l=b},ka=function(a,b,c,d){var e=O(null,null,null);e.g=new L(function(a,h){e.o=b?function(c){try{var e=b.call(d,c);a(e)}catch(C){h(C)}}:a;e.h=c?function(b){try{var e=c.call(d,b);a(e)}catch(C){h(C)}}:h});e.g.o=a;R(a,e);return e.g};L.prototype.F=function(a){this.g=0;K(this,2,a)};L.prototype.G=function(a){this.g=0;K(this,3,a)};
var K=function(a,b,c){0==a.g&&(a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.g=1,P(c,a.F,a.G,a)||(a.C=c,a.g=b,a.o=null,Q(a),3!=b||la(a,c)))},P=function(a,b,c,d){if(a instanceof L)return R(a,O(b||g,c||null,d)),!0;var e;if(a)try{e=!!a.$goog_Thenable}catch(h){e=!1}else e=!1;if(e)return a.then(b,c,d),!0;e=typeof a;if("object"==e&&null!=a||"function"==e)try{var k=a.then;if(n(k))return ma(a,k,b,c,d),!0}catch(h){return c.call(d,h),!0}return!1},ma=function(a,b,c,d,e){var k=!1,h=function(a){k||
(k=!0,c.call(e,a))},l=function(a){k||(k=!0,d.call(e,a))};try{b.call(a,h,l)}catch(q){l(q)}},Q=function(a){a.w||(a.w=!0,I(a.D,a))},na=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.l=null);return b};L.prototype.D=function(){for(var a=null;a=na(this);){var b=this.g,c=this.C;if(3==b&&a.h&&!a.s)for(var d=void 0,d=this;d&&d.s;d=d.o)d.s=!1;if(a.g)a.g.o=null,oa(a,b,c);else try{a.s?a.o.call(a.l):oa(a,b,c)}catch(e){S.call(null,e)}y(N,a)}this.w=!1}; var oa=function(a,b,c){2==b?a.o.call(a.l,c):a.h&&a.h.call(a.l,c)},la=function(a,b){a.s=!0;I(function(){a.s&&S.call(null,b)})},S=z;
var T=function(){this.h={};this.g={}};m(T);var U=function(a,b,c,d,e){this.reset(a,b,c,d,e)};U.prototype.g=null;var pa=0;U.prototype.reset=function(a,b,c,d,e){"number"==typeof e||pa++;d||da();this.h=b;delete this.g};U.prototype.getMessage=function(){return this.h};var V=function(a){this.o=a;this.h=this.l=this.g=null},W=function(a,b){this.name=a;this.value=b};W.prototype.toString=function(){return this.name};var qa=new W("SEVERE",1E3),ra=new W("CONFIG",700);V.prototype.getChildren=function(){this.h||(this.h={});return this.h};var sa=function(a){return a.l?a.l:a.g?sa(a.g):null};
V.prototype.log=function(a,b,c){if(a.value>=sa(this).value)for(n(b)&&(b=b()),a=new U(a,String(b),this.o),c&&(a.g=c),c="log:"+a.getMessage(),f.console&&(f.console.timeStamp?f.console.timeStamp(c):f.console.markTimeline&&f.console.markTimeline(c)),f.msWriteProfilerMark&&f.msWriteProfilerMark(c),c=this;c;)c=c.g};var X={},Y=null,ta=function(a){Y||(Y=new V(""),X[""]=Y,Y.l=ra);var b;if(!(b=X[a])){b=new V(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=ta(a.substr(0,c));c.getChildren()[d]=b;b.g=c;X[a]=b}return b};
var Z;Z=ta("image.collections.extension.Promises");var S=function(a){Z&&Z.log(qa,a.toString(),void 0)},ua=function(a,b,c){return function(d){var e=chrome.runtime.lastError;e?(d=T.v(),a&&(d.g[a]=(d.g[a]||0)+1),c(e.message||"Unknown Chrome API error")):(e=T.v(),a&&(e.h[a]=(e.h[a]||0)+1),b(d))}},va=function(a,b){return new L(function(c,d){chrome.tabs.sendMessage(a,b,ua("chrome.tabs.sendMessage",c,d))})},wa=function(){return new L(function(a,b){chrome.tabs.getCurrent(ua("chrome.tabs.getCurrent",a,b))})};
var xa=function(){};m(xa);(function(){xa.v();var a={type:"get_log_history"},b={type:"get_chrome_api_logs"};wa().then(function(c){c=c.openerTabId;return ja([va(c,a),va(c,b)])}).then(function(a){var b;b=document.createElement("pre");fa(b,a[0]+"\nChrome API calls:\n"+a[1]);ea(b)})})();

}catch(e){_DumpException(e)}
// Google Inc.
